data_generation:
  safe: False # checks before inserting data in db if set True
  aircrafts: 1100
  carriers: 15
  flights_per_aircraft: 15
  flights_per_aircraft_margin: 3
  flight_schedule_prefix : "SCH-ZZ-"
  paid_service: 0.08
  paid_service_score: 200
  loyality_program_score: 2000
  loyality_program: 0.003 # PROBABILITY
  pax_score: 50
  ssr_score: 100
  default_ssr_probability: 0.001
search:
  max_hop : 2 # max limit 2 
  downgrade: True
  upgrade: True
  skip_quantum: True # reduce time ( tries to do the same thing in classical way ) when set True
  use_inventory: False
  use_cabin_only: True
  neighboring_search: True # searh using same state airport
scores:
  connecting_score: 100
  default_ssr_score: 200
  default_scd1_score: 300
  default_scd2_score: 200
  cabins:
    F: 2000
    B: 1000
    P: 500
    E: 100
  loyalty:
    Silver: 1000
    Gold: 2000
    Platinum: 3000




# 0.30, 0.32, 0.28, 0.032, 0.03, 0.028, 0.0032, 0.003, 0.0028, 0.001