connecting:
  upper_limit: 3
  lower_limit: 1
  probability: 0.001
  score: 100
paid_service: 0.08
loyality_program: 0.003
paid_service_score: 200
loyality_program_score: 2000
pax_score: 50
safe: False
ssr_score: 100
min_arrival_score: 30
max_arrival_score: 70
min_departure_score: 30
max_departure_score: 70
downgrade: True
upgrade: True
connecting_score: 100
data_generation:
  aircrafts: 1100
  carriers: 15
  flights_per_aircraft: 15
  flights_per_aircraft_margin: 3
  flight_schedule_prefix : "SCH-ZZ-"
search:
  max_hop : 2
scores:
  default_ssr_score: 200
  default_scd2_score: 300
  default_scd3_score: 200
  cabins:
    F: 2000
    B: 1000
    P: 500
    E: 100
  loyalty:
    Silver: 1000
    Gold: 2000
    Platinum: 3000
probabilities:
  default_ssr_probability: 0.001




# 0.30, 0.32, 0.28, 0.032, 0.03, 0.028, 0.0032, 0.003, 0.0028, 0.001