# Generated by Django 4.2.7 on 2023-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ident', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('large_airport', 'Large Airport'), ('medium_airport', 'Medium Airport'), ('small_airport', 'Small Airport'), ('heliport', 'Heliport'), ('closed', 'Closed'), ('seaplane_base', 'Seaplane Base'), ('balloonport', 'Balloonport')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('continent', models.CharField(max_length=2, null=True)),
                ('continent_name', models.CharField(max_length=255, null=True)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_name', models.CharField(max_length=255)),
                ('iso_region', models.CharField(max_length=7)),
                ('local_region', models.CharField(max_length=255, null=True)),
                ('municipality', models.CharField(max_length=255, null=True)),
                ('scheduled_service', models.BooleanField()),
                ('gps_code', models.CharField(max_length=4, null=True)),
                ('iata_code', models.CharField(max_length=3, null=True)),
                ('local_code', models.CharField(max_length=4, null=True)),
                ('home_link', models.URLField(null=True)),
                ('wikipedia_link', models.URLField(null=True)),
                ('keywords', models.CharField(max_length=255, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
