# Generated by Django 4.1 on 2023-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ssr",
            old_name="srr_point",
            new_name="ssr_point",
        ),
    ]
