# Generated by Django 4.2.7 on 2023-11-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='iso_name',
        ),
    ]
