# Generated by Django 4.2.7 on 2023-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_classtype_lower_remove_classtype_upper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(null=True),
        ),
    ]
