# Generated by Django 4.2.7 on 2023-11-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_srr_point_ssr_ssr_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengergroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='passengergroup',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='passengerseat',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='passengerseat',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='passengerssr',
            name='pnr',
        ),
        migrations.RemoveField(
            model_name='passengerssr',
            name='ssr',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seatdistribution',
            name='seat_avail',
        ),
        migrations.AddField(
            model_name='classtype',
            name='cabin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.cabintype'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pnr',
            name='pnr',
            field=models.CharField(default='hello', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pnr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='pax',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ConnectingFlight',
        ),
        migrations.DeleteModel(
            name='PassengerGroup',
        ),
        migrations.DeleteModel(
            name='PassengerSeat',
        ),
        migrations.DeleteModel(
            name='PassengerSSR',
        ),
    ]
