# Generated by Django 4.2.7 on 2023-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_airport_iso_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('id_num', models.CharField(max_length=255)),
                ('id_callsign', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('registration', models.CharField(max_length=255)),
                ('owner_code', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
            ],
        ),
    ]
