# Generated by Django 4.2.7 on 2023-11-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='cabin_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SeatDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_count', models.IntegerField(default=0)),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.aircraft')),
                ('cabin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.cabintype')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.classtype')),
            ],
        ),
    ]
