# Generated by Django 4.2.7 on 2023-12-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flight_arrival_flight_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dst', to='flight.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='src',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='src', to='flight.airport'),
        ),
    ]
