# Generated by Django 4.2.7 on 2023-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_passengergroup_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='lower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classtype',
            name='upper',
            field=models.IntegerField(default=0),
        ),
    ]
