# Generated by Django 4.2.7 on 2023-11-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_cabintype_classtype_aircraft_cabin_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='id_callsign',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='id_num',
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('flight_time', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.aircraft')),
                ('arrival_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='flight.airport')),
                ('departure_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flight.airport')),
            ],
        ),
    ]
