# Generated by Django 4.2.7 on 2023-12-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_dst_flight_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='dep_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pnrpassenger',
            name='nationality',
            field=models.CharField(blank=True, default='IN', max_length=255, null=True),
        ),
    ]
