# Generated by Django 4.2.7 on 2023-11-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_classtype_lower_classtype_upper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatdistribution',
            name='cabin_type',
        ),
    ]
