# Generated by Django 4.2.7 on 2023-11-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_seatdistribution_cabin_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnr',
            old_name='seat_currency',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='seat_cabin',
        ),
        migrations.RemoveField(
            model_name='pnr',
            name='total_price',
        ),
        migrations.AddField(
            model_name='pnr',
            name='booking_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='flight.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnr',
            name='ssr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='pnr',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PnrFlightMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.pnr')),
            ],
        ),
    ]
