# Generated by Django 4.2.7 on 2023-12-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_pnr_dep_key_alter_pnr_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='ident',
            field=models.CharField(max_length=20),
        ),
    ]
