# Generated by Django 4.2.7 on 2023-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_aircraft_id_callsign_remove_aircraft_id_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
