# Generated by Django 4.2.7 on 2023-11-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_rename_seat_currency_pnr_currency_remove_pnr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='probability',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='ssr',
            name='probability',
            field=models.FloatField(default=0.1),
        ),
    ]
