# Generated by Django 4.2.7 on 2023-11-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_alter_aircraft_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
