# Generated by Django 4.2.7 on 2023-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_group_probability_ssr_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
