# Generated by Django 4.1 on 2023-11-24 07:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0008_alter_aircraft_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "phone_no",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="seatdistribution",
            name="seat_avail",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cabintype",
            name="type_name",
            field=models.CharField(
                choices=[
                    ("F", "First Cabin"),
                    ("J", "Second Cabin"),
                    ("Y", "Third Cabin"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="type_name",
            field=models.CharField(
                choices=[
                    ("A", "First Class"),
                    ("C", "Business Class"),
                    ("K", "Economy Class"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("green", "running"),
                    ("red", "cancelled"),
                    ("yellow", "landing or taking off"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="PNR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("total_tax", models.FloatField(default=0)),
                ("total_price", models.FloatField(default=0)),
                ("seat_currency", models.CharField(max_length=255)),
                ("paid_service", models.BooleanField(default=False)),
                ("group_booking", models.BooleanField(default=False)),
                ("loyalty_program", models.BooleanField(default=False)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flight.flight"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassengerSeat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("seat_number", models.CharField(max_length=255)),
                ("seat_price", models.FloatField(default=0)),
                ("seat_tax", models.FloatField(default=0)),
                ("seat_total", models.FloatField(default=0)),
                (
                    "ssr",
                    models.CharField(
                        choices=[
                            ("INFT", "Infant"),
                            ("WCHR", "Wheelchair, can walk"),
                            ("WCHS", "Wheelchair, can't climb stairs"),
                            ("WCHC", "Complete immobile"),
                            ("LANG", "Language restrictions"),
                            ("CHLD", "Child"),
                            ("MAAS", "Meet and assist - many reasons"),
                            ("UNMR", "Unaccompanied minor"),
                            ("BLND", "Blind"),
                            ("DEAF", "Deaf"),
                            ("EXST", "Large person taking up two seats"),
                            ("MEAL", "Meal request"),
                            ("NSST", "seat information"),
                            ("NRPS", "No seat request"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("paid_service", models.BooleanField(default=False)),
                ("loyalty_program", models.BooleanField(default=False)),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight.passenger",
                    ),
                ),
                (
                    "pnr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="flight.pnr",
                    ),
                ),
                (
                    "seat_cabin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight.cabintype",
                    ),
                ),
                (
                    "seat_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight.classtype",
                    ),
                ),
            ],
        ),
    ]
