# Generated by Django 4.1 on 2023-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0010_alter_passengerseat_pnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("green", "landed and open for entry"),
                    ("red", "landed and no entry"),
                    ("grey", "scheduled"),
                ],
                max_length=255,
            ),
        ),
    ]
