# Generated by Django 4.1 on 2023-11-24 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight", "0011_alter_flight_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraft",
            name="cabin_type",
        ),
    ]
